# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='entry',
            name='in_dorm',
            field=models.BooleanField(default=False, verbose_name='Is in dormitory?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
    ]
